### ISSUE TITLE
Trying wiki functionality, getting error there.

### ISSUE THREAD

**Issue by jasir** [undx/redmine_screenshot_paste#10]
Here is my log:

```
Started GET "/projects/dev-server-redmine/wiki/Redmine-wiki/edit" for 10.0.2.2 at Fri Dec 14 10:57:55 +0100 2012
Processing by WikiController#edit as HTML
  Parameters: {"id"=>"Redmine-wiki", "project_id"=>"dev-server-redmine"}
  Rendered plugins/redmine_screenshot_paste/app/views/issues/_screenshot.html.erb (2.2ms)
  Rendered attachments/_form.html.erb (7.4ms)
  Rendered plugins/redmine_screenshot_paste/app/views/wiki/edit.html.erb within layouts/base (585.6ms)
Completed 500 Internal Server Error in 637ms

ActionView::Template::Error (undefined method `preview_link' for #<#<Class:0x7f7855510408>:0x7f78555b6628>):
    38: </div>
    39:
    40: <p><%= submit_tag l(:button_save) %>
    41:    <%= preview_link({:controller => 'wiki', :action => 'preview', :project_id => @project, :id => @page.title }, 'w
iki_form') %></p>
    42: <%= wikitoolbar_for 'content_text' %>
    43: <% end %>
    44:
  plugins/redmine_screenshot_paste/app/views/wiki/edit.html.erb:41:in `_plugins_redmine_screenshot_paste_app_views_wiki_edi
t_html_erb___665038889_70077402415340'
  actionpack (3.2.6) lib/action_view/helpers/capture_helper.rb:40:in `capture'
  actionpack (3.2.6) lib/action_view/helpers/capture_helper.rb:187:in `with_output_buffer'
  actionpack (3.2.6) lib/action_view/helpers/capture_helper.rb:40:in `capture'
  actionpack (3.2.6) lib/action_view/helpers/form_helper.rb:607:in `fields_for'
  actionpack (3.2.6) lib/action_view/helpers/form_helper.rb:378:in `form_for'
  plugins/redmine_screenshot_paste/app/views/wiki/edit.html.erb:5:in `_plugins_redmine_screenshot_paste_app_views_wiki_edit
_html_erb___665038889_70077402415340'
  actionpack (3.2.6) lib/action_view/template.rb:145:in `send'
  actionpack (3.2.6) lib/action_view/template.rb:145:in `render'
  activesupport (3.2.6) lib/active_support/notifications.rb:125:in `instrument'
  actionpack (3.2.6) lib/action_view/template.rb:143:in `render'
  actionpack (3.2.6) lib/action_view/renderer/template_renderer.rb:47:in `render_template'
  actionpack (3.2.6) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  activesupport (3.2.6) lib/active_support/notifications.rb:123:in `instrument'
  activesupport (3.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.6) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.6) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  actionpack (3.2.6) lib/action_view/renderer/template_renderer.rb:46:in `render_template'
  actionpack (3.2.6) lib/action_view/renderer/template_renderer.rb:54:in `render_with_layout'
  actionpack (3.2.6) lib/action_view/renderer/template_renderer.rb:45:in `render_template'
  actionpack (3.2.6) lib/action_view/renderer/template_renderer.rb:18:in `render'
  actionpack (3.2.6) lib/action_view/renderer/renderer.rb:36:in `render_template'
  actionpack (3.2.6) lib/action_view/renderer/renderer.rb:17:in `render'
  actionpack (3.2.6) lib/abstract_controller/rendering.rb:110:in `_render_template'
  actionpack (3.2.6) lib/action_controller/metal/streaming.rb:225:in `_render_template'
  actionpack (3.2.6) lib/abstract_controller/rendering.rb:103:in `render_to_body'
  actionpack (3.2.6) lib/action_controller/metal/renderers.rb:28:in `render_to_body'
  actionpack (3.2.6) lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
  actionpack (3.2.6) lib/abstract_controller/rendering.rb:88:in `render'
  actionpack (3.2.6) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (3.2.6) lib/action_controller/metal/instrumentation.rb:40:in `render_without_wiki_extensions'
  activesupport (3.2.6) lib/active_support/core_ext/benchmark.rb:5:in `ms'
  /opt/bitnami/ruby/lib/ruby/1.8/benchmark.rb:308:in `realtime'
  activesupport (3.2.6) lib/active_support/core_ext/benchmark.rb:5:in `ms'
  actionpack (3.2.6) lib/action_controller/metal/instrumentation.rb:40:in `render_without_wiki_extensions'
  actionpack (3.2.6) lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
  activerecord (3.2.6) lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
  actionpack (3.2.6) lib/action_controller/metal/instrumentation.rb:39:in `render_without_wiki_extensions'
  plugins/redmine_wiki_extensions/lib/wiki_extensions_wiki_controller_patch.rb:54:in `render'
  actionpack (3.2.6) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  actionpack (3.2.6) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
  actionpack (3.2.6) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.6) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.6) lib/abstract_controller/callbacks.rb:18:in `process_action'
  activesupport (3.2.6) lib/active_support/callbacks.rb:480:in `_run__1394003979__process_action__708067161__callbacks'
  activesupport (3.2.6) lib/active_support/callbacks.rb:405:in `send'
  activesupport (3.2.6) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.6) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.6) lib/active_support/callbacks.rb:81:in `send'
  activesupport (3.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.6) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.6) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.6) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  activesupport (3.2.6) lib/active_support/notifications.rb:123:in `instrument'
  activesupport (3.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.6) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.6) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.6) lib/action_controller/metal/params_wrapper.rb:206:in `process_action'
  activerecord (3.2.6) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.6) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.6) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.6) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.6) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.6) lib/action_controller/metal.rb:246:in `action'
  actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.3) lib/journey/router.rb:68:in `call'
  journey (1.0.3) lib/journey/router.rb:56:in `each'
  journey (1.0.3) lib/journey/router.rb:56:in `call'
  actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:600:in `call'
  rack-openid (1.3.1) lib/rack/openid.rb:98:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.1) lib/rack/etag.rb:23:in `call'
  rack (1.4.1) lib/rack/conditionalget.rb:25:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.1) lib/rack/session/abstract/id.rb:205:in `context'
  rack (1.4.1) lib/rack/session/abstract/id.rb:200:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/cookies.rb:338:in `call'
  activerecord (3.2.6) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:473:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/callbacks.rb:28:in `call'
  activesupport (3.2.6) lib/active_support/callbacks.rb:405:in `_run__14559845__call__4__callbacks'
  activesupport (3.2.6) lib/active_support/callbacks.rb:405:in `send'
  activesupport (3.2.6) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.6) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.6) lib/active_support/callbacks.rb:81:in `send'
  activesupport (3.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.6) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.6) lib/rails/rack/logger.rb:26:in `call_app'
  railties (3.2.6) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.1) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.1) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.6) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.1) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/static.rb:62:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.6) lib/rails/engine.rb:479:in `call'
  railties (3.2.6) lib/rails/application.rb:220:in `call'
  railties (3.2.6) lib/rails/railtie/configurable.rb:30:in `send'
  railties (3.2.6) lib/rails/railtie/configurable.rb:30:in `method_missing'
  passenger (3.0.12) lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
  passenger (3.0.12) lib/phusion_passenger/abstract_request_handler.rb:520:in `accept_and_process_next_request'
  passenger (3.0.12) lib/phusion_passenger/abstract_request_handler.rb:275:in `main_loop'
  passenger (3.0.12) lib/phusion_passenger/rack/application_spawner.rb:206:in `start_request_handler'
  passenger (3.0.12) lib/phusion_passenger/rack/application_spawner.rb:171:in `send'
  passenger (3.0.12) lib/phusion_passenger/rack/application_spawner.rb:171:in `handle_spawn_application'
  passenger (3.0.12) lib/phusion_passenger/utils.rb:479:in `safe_fork'
  passenger (3.0.12) lib/phusion_passenger/rack/application_spawner.rb:166:in `handle_spawn_application'
  passenger (3.0.12) lib/phusion_passenger/abstract_server.rb:357:in `__send__'
  passenger (3.0.12) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
  passenger (3.0.12) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
  passenger (3.0.12) lib/phusion_passenger/abstract_server.rb:180:in `start'
  passenger (3.0.12) lib/phusion_passenger/rack/application_spawner.rb:129:in `start'
  passenger (3.0.12) lib/phusion_passenger/spawn_manager.rb:253:in `spawn_rack_application'
  passenger (3.0.12) lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
  passenger (3.0.12) lib/phusion_passenger/spawn_manager.rb:246:in `spawn_rack_application'
  passenger (3.0.12) lib/phusion_passenger/abstract_server_collection.rb:82:in `synchronize'
  passenger (3.0.12) lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
  passenger (3.0.12) lib/phusion_passenger/spawn_manager.rb:244:in `spawn_rack_application'
  passenger (3.0.12) lib/phusion_passenger/spawn_manager.rb:137:in `spawn_application'
  passenger (3.0.12) lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
  passenger (3.0.12) lib/phusion_passenger/abstract_server.rb:357:in `__send__'
  passenger (3.0.12) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
  passenger (3.0.12) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
  passenger (3.0.12) helper-scripts/passenger-spawn-server:99
```

**Comment by undx** [comment]
Hi, 
sorry for the late reply i had no time...
I've posted a commit that should fix the problem. 
Unfortunatly, for now i cannot test it on Redmine 2.0.x.
Please, check if it' s ok on 2.0.
Regards.

**Comment by alicezq** [comment]
hello,undx
I Itried to use this plugin ，but it still can not be used。
when I put it on my projects, it can operate normally，but will not be able to use it as a plug-in on bitnami.
Please try re-packaged into a plug-in.
I hope you can solve this problem，thank you very much.Waiting……

**Comment by undx** [comment]
Hello,
did you have a look at other issues concerning bitnami ? [here](https://github.com/undx/redmine_screenshot_paste/issues/7#issuecomment-11280964) and [here](https://github.com/undx/redmine_screenshot_paste/issues/6).
If the mentioned issues above didn't solve your problem, please send me more informations about your problem...

**Comment by alicezq** [comment]
hello,
the problem i have solved,i changed the codebase's value .but there still have some trouble.When I switch tabs, found it very slow response,initially loaded, when in fact it is very fast.So I think that is when I switch tabs, its exit and release resources was very slowlly .I do not know that my view is correct,Therefore, I hope that you can verify and solve it.
Thank you !~

**Comment by undx** [comment]
I think that more relevant to java's plugin, not a Redmine issue. 
It may also be slow, if you make screenshots of your whole desktop which is 2560x1440 pixels ! **;)**
